# -*- coding: utf-8 -*-
"""data cleaning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uk9ayntZejbeele-Xq-nVghQgeYlzgbq
"""

import pandas as pd

customer=pd.read_csv("/content/olist_customers_dataset.csv")

order=pd.read_csv("/content/olist_order_items_dataset.csv")

order_payments=pd.read_csv("/content/olist_order_payments_dataset.csv")

order_reviews = pd.read_csv("/content/olist_order_reviews_dataset.csv")

order_dataset=pd.read_csv("/content/olist_orders_dataset.csv")

products_dataset=pd.read_csv("/content/olist_products_dataset.csv")

seller_dataset=pd.read_csv("/content/olist_sellers_dataset.csv")

print(customer.head())

print(customer.shape)

print(order.head())

print(order.shape)

print(order_payments.head())

print(order_payments.shape)

print(order_reviews.head())

print(order_reviews.shape)

print(order_dataset.head())

print(order_dataset.shape)

print(products_dataset.head())

print(products_dataset.shape)

print(seller_dataset.head())

print(seller_dataset.shape)
lists=[customer,order,order_payments,order_reviews,order_dataset,products_dataset,seller_dataset]
for i in lists:
  print(i.duplicated())
  i.info()
  print(i.isnull().sum())
