# -*- coding: utf-8 -*-
"""data cleaning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uk9ayntZejbeele-Xq-nVghQgeYlzgbq
"""

import pandas as pd

customer=pd.read_csv("/content/olist_customers_dataset.csv")

order=pd.read_csv("/content/olist_order_items_dataset.csv")

order_payments=pd.read_csv("/content/olist_order_payments_dataset.csv")

order_reviews = pd.read_csv("/content/olist_order_reviews_dataset.csv")

order_dataset=pd.read_csv("/content/olist_orders_dataset.csv")

products_dataset=pd.read_csv("/content/olist_products_dataset.csv")

seller_dataset=pd.read_csv("/content/olist_sellers_dataset.csv")

print(customer.head())

print(customer.shape)

print(order.head())

print(order.shape)

print(order_payments.head())

print(order_payments.shape)

print(order_reviews.head())

print(order_reviews.shape)

print(order_dataset.head())

print(order_dataset.shape)

print(products_dataset.head())

print(products_dataset.shape)

print(seller_dataset.head())

print(seller_dataset.shape)
lists=[customer,order,order_payments,order_reviews,order_dataset,products_dataset,seller_dataset]
for i in lists:
  print(i.duplicated())
  i.info()
  print(i.isnull().sum())
# Check order status distribution
print("Order Status Distribution:")
print(orders['order_status'].value_counts())

# Keep only delivered orders
orders = orders[orders['order_status'] == 'delivered']

# Handle missing values in Orders
orders = orders.dropna(subset=[
    'order_approved_at',
    'order_delivered_customer_date'
])

# Handle missing values in Order Items
order_items = order_items.dropna()

# Handle missing values in Products
products['product_category_name'] = products['product_category_name'].fillna('Unknown')

products['product_name_lenght'] = products['product_name_lenght'].fillna(0)
products['product_description_lenght'] = products['product_description_lenght'].fillna(0)
products['product_photos_qty'] = products['product_photos_qty'].fillna(0)

products = products.dropna(subset=[
    'product_weight_g',
    'product_length_cm',
    'product_height_cm',
    'product_width_cm'
])

# Verify missing values after cleaning
print("\nOrders Missing Values:")
print(orders.isnull().sum())

print("\nOrder Items Missing Values:")
print(order_items.isnull().sum())

print("\nProducts Missing Values:")
print(products.isnull().sum())

# Check final dataset shapes
print("\nFinal Dataset Shapes:")
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)
print("Products:", products.shape)
# Merge Orders and Customers
cohort_df = pd.merge(
    orders,
    customers,
    on='customer_id',
    how='left'
)

# Merge Payments
cohort_df = pd.merge(
    cohort_df,
    payments,
    on='order_id',
    how='left'
)
# Verify merged dataset
print(cohort_df.head())
print(cohort_df.shape)
print(cohort_df.info())
# Calculate first purchase month of each customer
cohort_df['CohortMonth'] = (
    cohort_df.groupby('customer_unique_id')['order_purchase_timestamp']
             .transform('min')
             .dt.to_period('M')
)

# Verify
print(
    cohort_df[['customer_unique_id',
               'order_purchase_timestamp',
               'CohortMonth']].head()
)

# Save dataset
cohort_df.to_csv("cohort_dataset.csv", index=False)
#Week2
# Find first purchase month for each customer
cohort = orders.groupby('customer_id')['OrderMonth'].min().reset_index()
# Rename column
cohort.rename(columns={'OrderMonth': 'CohortMonth'}, inplace=True)
# Merge with orders dataset
orders = orders.merge(cohort, on='customer_id')
# Verify
print(orders[['customer_id', 'OrderMonth', 'CohortMonth']].head())
# Calculate year and month difference
year_diff = orders['OrderMonth'].dt.year - orders['CohortMonth'].dt.year
month_diff = orders['OrderMonth'].dt.month - orders['CohortMonth'].dt.month

# Create Cohort Index
orders['CohortIndex'] = year_diff * 12 + month_diff + 1

# Verify
print(orders[['customer_id','OrderMonth','CohortMonth','CohortIndex']].head())
